-- Data Mobile

-- Data boutik
insert into GALLOIS.TYPEMAGASIN (ID, VAL, DESCE)
values ('TYPMG000003', 'Boutik', 'Boutik');

-- Type produit
insert into GALLOIS.TYPE_PRODUIT (ID, VAL, DESCE)
values ('TP00004', 'Type_Lubrifiant', 'Produit en vente dans les magasins de type Boutik et Reservoir');


-- Produit
insert into GALLOIS.PRODUIT (ID, VAL, DESCE, IDTYPEPRODUIT, PUACHAT, PUVENTE, IDCATEGORIE, ISACHAT)
values ('PROD0010', 'Lub Veloce', 'Lub Veloce', 'TP00004', 1100, 1500, 'GRP000354', 1);
insert into GALLOIS.PRODUIT (ID, VAL, DESCE, IDTYPEPRODUIT, PUACHAT, PUVENTE, IDCATEGORIE, ISACHAT)
values ('PROD0011', 'Lub Force', 'Lub Force', 'TP00004', 4800, 5500, 'GRP000354', 1);


-- Boutiks de vente
insert into GALLOIS.MAGASIN (ID, VAL, IDPOINT, IDPRODUIT, IDTYPEMAGASIN)
values ('BTK011', 'Boutik Tanjombato', 'PNT000124', 'PROD0010', 'TYPMG000003');
insert into GALLOIS.MAGASIN (ID, VAL, IDPOINT, IDPRODUIT, IDTYPEMAGASIN)
values ('BTK012', 'Boutik Andoram', 'PNT000123', 'PROD0011', 'TYPMG000003');

-- Cuve de vente
insert into GALLOIS.MAGASIN (ID, VAL, IDPOINT, IDPRODUIT, IDTYPEMAGASIN)
values ('RES011', 'Cuve Tanjombato', 'PNT000124', 'PROD0010', 'TYPMG000001');
insert into GALLOIS.MAGASIN (ID, VAL, IDPOINT, IDPRODUIT, IDTYPEMAGASIN)
values ('RES012', 'Cuve Andoram', 'PNT000123', 'PROD0011', 'TYPMG000001');


-- Inventaire boutik
insert into GALLOIS.INVENTAIRE (ID, DATY, DESIGNATION, IDMAGASIN, ETAT)
values ('IVT000101', TO_DATE('2024-10-01', 'YYYY-MM-DD'), 'Inventaire Alakamisy', 'BTK011', 11);
insert into GALLOIS.INVENTAIREFILLE(ID, IDINVENTAIRE, IDPRODUIT, EXPLICATION, QUANTITETHEORIQUE, QUANTITE)
values ('IVTFI000101', 'IVT000101', 'PROD0010', 'Inventaire Alakamisy zero', 0, 0);

insert into GALLOIS.INVENTAIRE (ID, DATY, DESIGNATION, IDMAGASIN, ETAT)
VALUES ('IVT000102', TO_DATE('2024-10-01', 'YYYY-MM-DD'), 'Inventaire Alakamisy', 'BTK012', 11);
insert into GALLOIS.INVENTAIREFILLE(ID, IDINVENTAIRE, IDPRODUIT, EXPLICATION, QUANTITETHEORIQUE, QUANTITE)
values ('IVTFI000102', 'IVT000102', 'PROD0011', 'Inventaire Alakamisy zero', 0, 0);

-- Inventaire cuve
insert into GALLOIS.INVENTAIRE (ID, DATY, DESIGNATION, IDMAGASIN, ETAT)
values ('IVT000103', TO_DATE('2024-10-01', 'YYYY-MM-DD'), 'Inventaire Alakamisy', 'RES011', 11);
insert into GALLOIS.INVENTAIREFILLE(ID, IDINVENTAIRE, IDPRODUIT, EXPLICATION, QUANTITETHEORIQUE, QUANTITE)
values ('IVTFI000103', 'IVT000103', 'PROD0010', 'Inventaire Alakamisy zero', 0, 0);

insert into GALLOIS.INVENTAIRE (ID, DATY, DESIGNATION, IDMAGASIN, ETAT)
VALUES ('IVT000104', TO_DATE('2024-10-01', 'YYYY-MM-DD'), 'Inventaire Alakamisy', 'RES012', 11);
insert into GALLOIS.INVENTAIREFILLE(ID, IDINVENTAIRE, IDPRODUIT, EXPLICATION, QUANTITETHEORIQUE, QUANTITE)
values ('IVTFI000104', 'IVT000104', 'PROD0011', 'Inventaire Alakamisy zero', 0, 0);


-- Entree Stock lub boutik
insert into GALLOIS.MVTSTOCK(ID, DESIGNATION, IDMAGASIN, IDTYPEMVSTOCK, DATY, ETAT)
values ('MVTST001', 'Rav lub boutik zero', 'BTK011', 'TPMVST000001', TO_DATE('2024-10-22', 'YYYY-MM-DD'), 11);
insert into GALLOIS.MVTSTOCKFILLE(ID, IDMVTSTOCK, IDPRODUIT, ENTREE, SORTIE)
values ('MVTSFI001', 'MVTST001', 'PROD0010', 500, 0);
insert into GALLOIS.MVTSTOCK(ID, DESIGNATION, IDMAGASIN, IDTYPEMVSTOCK, DATY, ETAT)
values ('MVTST002', 'Rav lub boutik zero', 'BTK012', 'TPMVST000001', TO_DATE('2024-10-22', 'YYYY-MM-DD'), 11);
insert into GALLOIS.MVTSTOCKFILLE(ID, IDMVTSTOCK, IDPRODUIT, ENTREE, SORTIE)
values ('MVTSFI002', 'MVTST002', 'PROD0011', 500, 0);

-- Entree Stock lub cuve
insert into GALLOIS.MVTSTOCK(ID, DESIGNATION, IDMAGASIN, IDTYPEMVSTOCK, DATY, ETAT)
values ('MVTST003', 'Rav lub reservoir zero', 'RES011', 'TPMVST000001', TO_DATE('2024-10-22', 'YYYY-MM-DD'), 11);
insert into GALLOIS.MVTSTOCKFILLE(ID, IDMVTSTOCK, IDPRODUIT, ENTREE, SORTIE)
values ('MVTSFI003', 'MVTST003', 'PROD0010', 500, 0);
insert into GALLOIS.MVTSTOCK(ID, DESIGNATION, IDMAGASIN, IDTYPEMVSTOCK, DATY, ETAT)
values ('MVTST004', 'Rav lub reservoir zero', 'RES012', 'TPMVST000001', TO_DATE('2024-10-22', 'YYYY-MM-DD'), 11);
insert into GALLOIS.MVTSTOCKFILLE(ID, IDMVTSTOCK, IDPRODUIT, ENTREE, SORTIE)
values ('MVTSFI004', 'MVTST004', 'PROD0011', 500, 0);



-- Views
CREATE OR REPLACE VIEW v_magasin_lubrifiant AS
select m.*
from PRODUIT p
         join magasin m
              on m.IDPRODUIT = p.ID
where p.IDTYPEPRODUIT = 'TP00004'
